### ISSUE TITLE
Fixed at the bottom of the View

### ISSUE THREAD

**Issue by HZSamir** [cesardeazevedo/react-native-bottom-sheet-behavior#17]
Hello again,
I'm having all the trouble in the world trying to fix this element to the bottom of my view. What I aim to do is something like this:

![rsz_screenshot_from_2017-02-05_16-04-24](https://cloud.githubusercontent.com/assets/4499783/22627197/56c86688-ebbe-11e6-8ba5-e0e4bc8b0cc8.png)

with the markup something along the lines of:
```javascript
<View>
  <ScrollView>
  // My list
  </ScrollView>
  <BottomSheet>
</View>
```

With the BottomSheet element always at the bottom of the screen and toggling it brings it in front of my scrollView, however I scroll the scrollView.

However I try to it though, either my BottomSheet element is at the bottom of the scrollView, not of the screen, or it is indeed at the bottom of the screen, but then the CoordinatorLayout takes most of the space in the scrollView, pushing everything on top of it, or finally, the BottomSheet element appears correctly, but when toggled it goes up just a few pixels up, not showing what it has inside.

I'm practically at my wit's end, I have no trouble with positioning in pure CSS, or Flex for that matter, but RN  is testing my patience.

I hope you'll excuse this not-quite-an-issue, for I feel that the issue may stem from the CoordinatorLayout component.

Thank you.

**Comment by cesardeazevedo** [comment]
Hi, thank you for the feedback.

i am not sure if i understood your problem properly, but i completely understand your frustration, let me tell your some considerations.

1. Everything should must be inside the `CoordinatorLayout`.
2. Define a `backgroundColor` on the top containers, there's some weird behavior on the views that they don't render properly, i already spent hours debugging trying to figure out what's going on when i was developing this component.
3. I recommend you define a `height` from `Dimensions.get('window')` on the content `View` instead of use `flex: 1`, it might solve your problem, that's why your ScrollView doesn't fill the hole View.
4. Be careful with `flex: 1`, it can easily become a mess, after react-native 0.36.0 they [changed](https://github.com/facebook/react-native/commit/0a9b6bedb312eba22c5bc11498b1cc41363e5f27) the flexbox behavior, and you should be careful when and where to use `flex: 1`

I prepared this gist for you, https://gist.github.com/cesardeazevedo/b10f28c0b9e5ee9b76fa05c0eb73bb4a
i hope i have understood correctly your situation, let me know if you got it.

**Comment by HZSamir** [comment]
Thank you again @cesardeazevedo You are a lifesaver.
Good day :)
